import { graphitePurple } from './graphitePurple.ts'
import type { ThemeDefinition } from './types.ts'

export const noirGold: ThemeDefinition = {
  id: 'noir-gold',
  name: '黑金女仆',
  colorScheme: 'dark',
  background: '#19181a',
  tokens: {
    ...graphitePurple.tokens,
    '--theme-text': '#eee8df',
    '--theme-secondary': '#d2c6b6',
    '--theme-muted': '#b5a89a',
    '--theme-faint': '#aa9780',
    '--theme-surface-rgb': '35,33,34',
    '--theme-raised-rgb': '44,41,41',
    '--theme-chrome-rgb': '28,26,27',
    '--theme-border-rgb': '191,157,106',
    '--theme-accent': '#d0ae75',
    '--theme-accent-rgb': '208,174,117',
    '--theme-accent-text': '#efd7ad',
    '--theme-inset': '#1c1a1c',
    '--theme-control-top': '#312c2b',
    '--theme-control-bottom': '#252223',
    '--theme-hover-top': '#3c342c',
    '--theme-hover-bottom': '#302923',
    '--theme-menu-top': '#302b28',
    '--theme-menu-bottom': '#211e20',
    '--theme-primary-start': '#d2b07b',
    '--theme-primary-end': '#b9915c',
    '--theme-primary-hover-start': '#dfc18e',
    '--theme-primary-hover-end': '#c6a16b',
    '--theme-on-primary': '#241b13',
    '--theme-on-check': '#241b13',
    '--theme-on-danger': '#fff1f3',
    '--theme-toggle-off': '#51473b',
    '--theme-toggle-start': '#aa8151',
    '--theme-toggle-end': '#cfab73',
    '--theme-toggle-knob': '#c3b8aa',
    '--theme-toggle-knob-active': '#fff5e5',
    '--theme-danger': '#e0a0a6',
    '--theme-danger-rgb': '213,140,148',
    '--theme-danger-hover': '#f0bcc0',
    '--theme-danger-start': '#995365',
    '--theme-danger-end': '#7c4458',
    '--theme-success': '#a2c8a4',
    '--theme-success-rgb': '142,190,146',
    '--theme-neutral-port': '#a39a91'
  },
  artwork: {
    src: './themes/noir-gold/ai-chan.png',
    anchor: 'bottom-left',
    heightRatio: .55,
    minHeight: 180,
    maxHeight: 380,
    opacity: .45,
    interactionOpacity: .2
  },
  libraryOrnament: { cornerMask: './themes/noir-gold/corner.svg', opacity: .65 }
}
